version: '3.5'

services:
  rabbit:
    container_name: symfony-api-platform-rabbitmq
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./docker:/etc/rabbitmq
#      - ./docker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 54353:15672
      - 25672:25672
    networks:
      - symfony-api-platform-network

networks:
  symfony-api-platform-network:
    external: true
